# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb261770fc79bfe28f2377b5ce86d68d75d13f214df1854745b59234fcd97d21f67bcd7694e0773fa5c2a2c11fd78cd511666d9376d48b22cf8ee012084b0bf

test:
  secret_key_base: 6e0d41c396b14a60595a5aa80049b40386bd2dfd45a08b2dbd06c268282ba04e479ab826926ad9b8ead0b0dd41bc91573366eb0a720ce29fe18cbe4f07b6803e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
